(* ::Package:: *)

(* ::Text:: *)
(*This notebook and the associated Mathematica package make user-defined y vs x plots of species occurring in the MWC model. It relies on the existence of a MWC data set as produced by MWCGenerateDataSet.m.*)
(*It and the associated Mathematica package are*)
(**)
(*Copyright (C), 2012,*)
(*David M. Morgan, Ph.D.*)
(*dmorgan@stfx.ca*)
(*St. Francis Xavier University, Angitonish, NS, Canada*)
(*Under the terms of the G.N.U. General Public License Version 3:00 or later.*)
(*http://www.gnu.org/licenses/gpl.html*)


MWCPlot[
YString_, XString_, MWCDataSet_, ColourArgument_
] := Module[
{
YLIST,
XLIST,
XYLIST,
OUTPUT
},
YLIST = Which[
YString == "PO2", #[[1]] & /@ MWCDataSet,
YString == "freeO2", #[[2]] & /@ MWCDataSet,
YString == "Y", #[[3]] & /@ MWCDataSet,
YString == "TState", #[[4]] & /@ MWCDataSet,
YString == "RState", #[[5]] & /@ MWCDataSet,
YString == "fTState",#[[4]] / (#[[4]] + #[[5]]) & /@ MWCDataSet,
YString == "fRState", #[[5]] / (#[[4]] + #[[5]]) & /@ MWCDataSet,
YString == "T4O20", #[[6]] & /@ MWCDataSet,
YString == "T4O21", #[[7]] & /@ MWCDataSet,
YString == "T4O22", #[[8]] & /@ MWCDataSet,
YString == "T4O23", #[[9]] & /@ MWCDataSet,
YString == "T4O24", #[[10]] & /@ MWCDataSet,
YString == "R4O20", #[[11]] & /@ MWCDataSet,
YString == "R4O21", #[[12]] & /@ MWCDataSet,
YString == "R4O22", #[[13]] & /@ MWCDataSet,
YString == "R4O23", #[[14]] & /@ MWCDataSet,
YString == "R4O24", #[[15]] & /@ MWCDataSet,
YString == "fT4O20", #[[6]] / (#[[4]] + #[[5]]) & /@ MWCDataSet,
YString == "fT4O21", #[[7]] / (#[[4]] + #[[5]]) & /@ MWCDataSet,
YString == "fT4O22", #[[8]] / (#[[4]] + #[[5]]) & /@ MWCDataSet,
YString == "fT4O23", #[[9]] / (#[[4]] + #[[5]]) & /@ MWCDataSet,
YString == "fT4O24", #[[10]] / (#[[4]] + #[[5]]) & /@ MWCDataSet,
YString == "fR4O20", #[[11]] / (#[[4]] + #[[5]]) & /@ MWCDataSet,
YString == "fR4O21", #[[12]] / (#[[4]] + #[[5]]) & /@ MWCDataSet,
YString == "fR4O22", #[[13]] / (#[[4]] + #[[5]]) & /@ MWCDataSet,
YString == "fR4O23", #[[14]] / (#[[4]] + #[[5]]) & /@ MWCDataSet,
YString == "fR4O24", #[[15]] / (#[[4]] + #[[5]]) & /@ MWCDataSet
];
XLIST=Which[
XString=="PO2",#[[1]]&/@MWCDataSet,
XString=="freeO2",#[[2]]&/@MWCDataSet,
XString=="Y",#[[3]]& /@ MWCDataSet,
XString=="TState",#[[4]]&/@MWCDataSet,
XString=="RState",#[[5]]&/@MWCDataSet,
XString=="fTState",#[[4]]/(#[[4]]+#[[5]])&/@MWCDataSet,
XString=="fRState",#[[5]]/(#[[4]]+#[[5]])&/@MWCDataSet,
XString=="T4O20",#[[6]]&/@MWCDataSet,
XString=="T4O21",#[[7]]&/@MWCDataSet,
XString=="T4O22",#[[8]]&/@MWCDataSet,
XString=="T4O23",#[[9]]&/@MWCDataSet,
XString=="T4O24",#[[10]]&/@MWCDataSet,
XString=="R4O20",#[[11]]&/@MWCDataSet,
XString=="R4O21",#[[12]]&/@MWCDataSet,
XString=="R4O22",#[[13]]&/@MWCDataSet,
XString=="R4O23",#[[14]]&/@MWCDataSet,
XString=="R4O24",#[[15]]&/@MWCDataSet,
XString=="fT4O20",#[[6]]/(#[[4]]+#[[5]])&/@MWCDataSet,
XString=="fT4O21",#[[7]]/(#[[4]]+#[[5]])&/@MWCDataSet,
XString=="fT4O22",#[[8]]/(#[[4]]+#[[5]])&/@MWCDataSet,
XString=="fT4O23",#[[9]]/(#[[4]]+#[[5]])&/@MWCDataSet,
XString=="fT4O24",#[[10]]/(#[[4]]+#[[5]])&/@MWCDataSet,
XString=="fR4O20",#[[11]]/(#[[4]]+#[[5]])&/@MWCDataSet,
XString=="fR4O21",#[[12]]/(#[[4]]+#[[5]])&/@MWCDataSet,
XString=="fR4O22",#[[13]]/(#[[4]]+#[[5]])&/@MWCDataSet,
XString=="fR4O23",#[[14]]/(#[[4]]+#[[5]])&/@MWCDataSet,
XString=="fR4O24",#[[15]]/(#[[4]]+#[[5]])&/@MWCDataSet
];
XYLIST = Transpose[
{XLIST, YLIST}
];
OUTPUT = ListPlot[
XYLIST, 
PlotRange -> All (*{All, {0,1}}*),
PlotStyle -> {ColourArgument, PointSize[0.015]}
]
]

"Function MWCPlot

Usage:  

MWCPlot[\[IndentingNewLine]YString_, XString_, MWCDataSet_, ColourArgument_\[IndentingNewLine]]

in which each of 
	YString and
	XString
may take on any of the following values:
	PO2, freeO2, Y, 
	TState, RState, fTState, fRState, 
	T4O20, T4O21, T4O22, T4O23, T4O24, 
	R4O20, R4O21, R4O22, R4O23, R4O24, 
	fT4O20, fT4O21, fT4O22, fT4O23, fT4O24,
	fR4O20, fR4O21, fR4O22, fR4O23, fR4O24.

	MWCDataSet\t\tis the name of a dataset generated by
\t\t\t\t\t  MWCGenerateDataSet
	ColourArgument\tis the desired colour for the plot."
